### ISSUE TITLE
Acho interessante deixar compatível com typescript

### ISSUE THREAD

**Issue by XavierJece** [brunobertolini/remask#7]

**Comment by guitexa** [comment]
Tem previsão para tornar compatível com o Typescript? Gostei muito da lib

**Comment by educbraga** [comment]
+1

**Comment by pedrorossato** [comment]
+1

**Comment by Nikaum-js** [comment]
Quando vai ser compatível com typescript?

**Comment by Nikaum-js** [comment]
> Não tenho previsão pessoal, ando bem sem tempo, mas se alguém quiser fazer uma PR fica a vontade! :)

Eu nunca fiz uma contribuição para uma lib, sinceramente não sei nem como começar. Mas eu vou tentar fazer essa feature, vai ser um grande desafio/aprendizado, logo logo eu mando o PR :eyes:

**Comment by brunobertolini** [comment]
> > Não tenho previsão pessoal, ando bem sem tempo, mas se alguém quiser fazer uma PR fica a vontade! :)
> 
> Eu nunca fiz uma contribuição para uma lib, sinceramente não sei nem como começar. Mas eu vou tentar fazer essa feature, vai ser um grande desafio/aprendizado, logo logo eu mando o PR 👀

Boa! Pra tudo tem uma primeira vez na vida hehe.

Você pode começar fazendo um fork (tem um botão de fork lá do lado do start no repositorio). Isso vai copiar o repo pra sua conta. Ai você desenvolve normalmente, como se fosse um repo seu, com commits normalmente. Quando achar que ta pronto, abre uma PR do seu repo pra esse aqui :)

**Comment by bm2dev** [comment]
@brunobertolini Fizeram um PR  (#22)  com a adição do suporte ao typescript, mas não linkaram com esse issue, se você puder dar um merge ajudaria muito, valeu!

**Comment by brunobertolini** [comment]
@bm2dev boa, obrigado por avisar. Merged! Em breve libero a versão no npm 👊

**Comment by brunobertolini** [comment]
[Versão com TS](https://www.npmjs.com/package/remask), e agora, sem nenhuma dependência extra :)
